---
abstract: 'JS minifying output filter'
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires:
  Apache::Test: 1.12
configure_requires:
  Apache::Test: 1.12
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-Filter-Minifier-JavaScript
provides:
  Apache2::Filter::Minifier::JavaScript:
    file: lib/Apache2/Filter/Minifier/JavaScript.pm
    version: 1.06
recommends:
  JavaScript::Minifier::XS: 0
requires:
  JavaScript::Minifier: 0
  Time::HiRes: 0
  mod_perl2: 2
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.06
